// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU4RnJcoSOhbijrLNx2fezWKGaZ1EGP5c',
    appId: '1:499283570958:web:06232930a0f8838368275f',
    messagingSenderId: '499283570958',
    projectId: 'namer-441a6',
    authDomain: 'namer-441a6.firebaseapp.com',
    storageBucket: 'namer-441a6.firebasestorage.app',
    measurementId: 'G-DMD36L7EYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXpM2T514-Mz0Ph7ImmCh1DlhVIH1Tiak',
    appId: '1:499283570958:android:583f757f1100ba6868275f',
    messagingSenderId: '499283570958',
    projectId: 'namer-441a6',
    storageBucket: 'namer-441a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgbCmKgUxn4Wyi_0FcGhjnhN5eZfDxAj4',
    appId: '1:499283570958:ios:2744e8c36d5f2a9968275f',
    messagingSenderId: '499283570958',
    projectId: 'namer-441a6',
    storageBucket: 'namer-441a6.firebasestorage.app',
    iosBundleId: 'com.pixelmonks.namer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgbCmKgUxn4Wyi_0FcGhjnhN5eZfDxAj4',
    appId: '1:499283570958:ios:6d7576948881e2c268275f',
    messagingSenderId: '499283570958',
    projectId: 'namer-441a6',
    storageBucket: 'namer-441a6.firebasestorage.app',
    iosBundleId: 'com.pixelmonks.namer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU4RnJcoSOhbijrLNx2fezWKGaZ1EGP5c',
    appId: '1:499283570958:web:390436940024fe6868275f',
    messagingSenderId: '499283570958',
    projectId: 'namer-441a6',
    authDomain: 'namer-441a6.firebaseapp.com',
    storageBucket: 'namer-441a6.firebasestorage.app',
    measurementId: 'G-JWJQCDW3LW',
  );
}
