#!/bin/bash

# Copies and resizes image assets from a source image file 'src' into a destination directory 'dst'.
# Example from root directory of project:
#   tools/make-icons assets/images/namer.png .

if [ $# -ne 2 ]; then
  echo "Usage: $0 <src-image> <dest-dir>"
  exit 1
fi

src="$1"
dst="$2"

# Check if src exists and is a regular file
if [ ! -f "$src" ]; then
  echo "error: src does not exist or is not a regular file: $src"
  echo "Usage: $0 <src-image> <dest-dir>"
  exit 1
fi

# Check if dst exists and is a directory
if [ ! -d "$dst" ]; then
  echo "error: dst does not exist or is not a directory: $dst"
  echo "Usage: $0 <src-image> <dest-dir>"
  exit 1
fi

# ios

sips -Z 1024 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png"
sips -Z 20 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png"
sips -Z 40 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png"
sips -Z 60 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png"
sips -Z 29 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png"
sips -Z 58 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png"
sips -Z 87 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png"
sips -Z 40 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png"
sips -Z 80 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png"
sips -Z 120 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png"
sips -Z 120 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png"
sips -Z 180 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png"
sips -Z 76 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png"
sips -Z 152 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png"
sips -Z 167 "$src" --out "$dst/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png"

# macos

sips -Z 16 "$src" --out "$dst/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png"
sips -Z 1024 "$src" --out "$dst/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png"
sips -Z 256 "$src" --out "$dst/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png"
sips -Z 64 "$src" --out "$dst/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png"
sips -Z 512 "$src" --out "$dst/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png"
sips -Z 128 "$src" --out "$dst/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png"
sips -Z 32 "$src" --out "$dst/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png"

# Example command lists existing image dimensions:
#
# $ sips -g pixelWidth -g pixelHeight "ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png"
#     ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
#       pixelWidth: 40
#       pixelHeight: 40
